replicaCount: 1

image:
  repository: ghcr.io/sokyutukumo/symfony-app
  pullPolicy: IfNotPresent
  tag: "94b19ed"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx" # 使用している Ingress Controller（例: nginx, alb, traefik など）
  annotations:
    # クラウドやコントローラーに応じた Annotation を記述（例: Cert-Manager 連携など）
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: symfony-app.local # ご利用のドメイン名やローカルドメインを指定
      paths:
        - path: /
          pathType: Prefix
  tls: [] 

database:
  enabled: true
  host: "postgres-service"
  port: 5432
  name: "symfony_db"
  user: "symfony_user"
  password: "symfony_password" # 実務では Secret 等で管理

migration:
  enabled: true 
