apiVersion: v1
kind: Service
metadata:
  name: symfony-app-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: symfony-app
