apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-symfony-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-symfony-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-symfony-app
    spec:
      containers:
      - name: symfony-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?serverVersion=16&charset=utf8"
