{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-migration-{{ randAlphaNum 5 | lower }}
  annotations:
    # Argo CD のフック設定: Sync (デプロイ) の前に実行する
    argocd.argoproj.io/hook: PreSync
    # 前回の Job を削除してから実行するポリシー
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  # 失敗時のリトライ回数
  backoffLimit: 2
  template:
    metadata:
      name: db-migration
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z -w 2 {{ .Values.database.host }} {{ .Values.database.port }}; do echo waiting for db; sleep 2; done;']
      containers:
      - name: db-migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /var/www/html
        command: ["php", "/var/www/bin/console", "doctrine:migrations:migrate", "--no-interaction"]
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?serverVersion=16&charset=utf8"
{{- end -}}
